### ISSUE TITLE
ios下持续定位回调收不到

### ISSUE THREAD

**Issue by druphliu** [yinglight/amap#1]
android可以持续收到，ios不行。
版本ios13

**Comment by yinglight** [comment]
好谢谢了，xcode中updateLocation勾选了吗？我这几天看看。

**Comment by druphliu** [comment]
勾选了的 我debug看定位是在持续，但是回调到js失败 也没报错

**Comment by druphliu** [comment]
找到问题了 应当是ios代码有问题 在打包后的文件CDVPluginResult.m里面89行keepCallback = [NSNumber numberWithBool:NO];改为keepCallback = [NSNumber numberWithBool:YES];就好了

**Comment by druphliu** [comment]
找到问题了 ios你没加 GoDelLocation.m 151行添加：
[commandResult setKeepCallback:[NSNumber numberWithBool:YES]];
就可以了

**Comment by yinglight** [comment]
好的谢谢啦
